baseurl = "/"
languageCode = "en-us"
title = "MAGStock 8"

[params]
  description = "MAGStock is a 4-day outdoor festival celebrating camping, video games, and video game music."
  date = "June 7-10, 2018"

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Events"
    url = "/#events"
    weight = 2

[[menu.main]]
    name = "Music"
    url = "/music"
    weight = 3

[[menu.main]]
    name = "Visualists"
    url = "/visualists"
    weight = 4

[[menu.main]]
    name = "Rules"
    url = "/rules-n-guidelines"
    weight = 5

[[menu.main]]
    name = "FAQ"
    url = "/faq"
    weight = 6
    
[[menu.main]]
    name = "Volunteer"
    url = "/#volunteer"
    weight = 7
