baseurl = "/"
languageCode = "en-us"
title = "MAGStock 8"

[params]
  description = "MAGWest is a 3-day festival celebrating video games, video game music, and the culture of people who create them."
  date = "June 10-12, 2018"

[[menu.main]]
    name = "Tickets: $70"
    url = "/#tickets"
    weight = 1

[[menu.main]]
    name = "Music"
    url = "/"
    weight = 2

[[menu.main]]
    name = "Where To Go"
    url = "/#where-to-go"
    weight = 3

[[menu.main]]
    name = "What To Bring"
    url = "/#what-to-bring"
    weight = 4

[[menu.main]]
    name = "Rules"
    url = "/#rules-n-guidelines"
    weight = 5

[[menu.main]]
    name = "Volunteer"
    url = "/volunteer"

[[menu.main]]
    name = "FAQ"
    url = "/faq"
    weight = 6

[[menu.main]]
    name = "Community"
    url = "/community"
    weight = 7
